clients/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as v
from django.contrib.auth import authenticate, login
from . import views
app_name="clients"
urlpatterns=[
    #homepage
    path('index/',views.index, name='index'),
    
    #login
    path('login/',v.LoginView.as_view(template_name='clients/login.html'), name='login'),
    
    
    #logout
    path('logout/', views.logout_view, name='logout'),
    
    #register
    path('register/',views.register, name='register'),
    
]

sample/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('samples.urls')),
   
    path('service_providers/', include('service_providers.urls')),
    path('clients/', include('clients.urls')),
]

samples/urls.py
from django.urls import path
from . import views

app_name="samples"
urlpatterns=[
    #homepage
    path('',views.index, name='index'),
    
    #to display the service provider offers
    path('service_provider/', views.service_provider, name='service_provider'),
    
    #to display clients
    path('service_providers/', views.service_providers, name='service_providers'),
    
    #for sending confirmation emails
    path('send_email/', views.send_email, name='send_email'),
    
    
    
]

service_providers/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as v
from django.contrib.auth import authenticate, login
from . import views
app_name="service_providers"
urlpatterns=[
    #homepage
    path('index/',views.index, name='index'),
    path('login/',v.LoginView.as_view(template_name='service_providers/login.html'), name='login'),
     
    path('logout/', views.logout_view, name='logout'),
    path('register/',views.register, name='register'),
    
    path('new_service/', views.new_service, name='new_service'),
]

samples/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class Service_Provider(models.Model):
    owner=models.ForeignKey(User,on_delete=models.CASCADE)
    service_name=models.CharField(max_length=200, default='')
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        """return the name of the service provider"""
        return self.service_name
    
    
        
class Client(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    text=models.CharField(max_length=200, default='')
    
    def __str__(self):
        """return the name of the client"""
        return self.text

    

service_providers/models.py
from django.db import models

# Create your models here.

service_providers/forms.py
from django import forms
from samples.models import Service_Provider

class ServiceProviderForm(forms.ModelForm):
    class Meta:
        model=Service_Provider
        fields=['service_name','text']
        labels={'text':'','service_name':''}

clients/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

def index(request):
    """index page for client"""
    return render(request, 'clients/index.html')




def logout_view(request):
    """logout view"""
    logout(request)
    return HttpResponseRedirect(reverse('samples:index'))

def register(request):
    """register view"""
    if request.method != 'POST':
        form=UserCreationForm()
    else:
        form=UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user=form.save()
            authenticate_user=authenticate(username=new_user.username, password=request.POST['password1'])
            login(request,authenticate_user)
            return HttpResponseRedirect(reverse('samples:service_providers'))
    context={'form':form}
    return render(request,'clients/register.html',context)

samples/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404,HttpResponse
from django.urls import reverse

from .models import Service_Provider
from .task import send_email_task


def index(request):
    """index page"""
    return render(request, 'samples/index.html')


def service_provider(request):
    """display all services by the particular service provider"""
    
    service=Service_Provider.objects.filter(owner=request.user).order_by('date_added')
    #if service.owner != request.user:
    #    raise Http404
    context={'service':service}
    return render(request,'samples/service_provider.html',context)


def service_providers(request):
    """display all service provider"""
    services=Service_Provider.objects.all()
    
    context={'services':services}
    return render(request,'samples/service_providers.html',context)


def send_email(request):
    """to send email through celery"""
    send_email_task.delay()
    return HttpResponse("Email Sent!!")

service_providers/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import ServiceProviderForm


def index(request):
    return render(request, 'service_providers/index.html')

def login_request(request):
    form = AuthenticationForm()
    return render(request = request,
                  template_name = "users/login_request.html",
                  context={"form":form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('samples:index'))

def register(request):
    if request.method != 'POST':
        form=UserCreationForm()
    else:
        form=UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user=form.save()
            authenticate_user=authenticate(username=new_user.username, password=request.POST['password1'])
            login(request,authenticate_user)
            return HttpResponseRedirect(reverse('samples:service_provider'))
    context={'form':form}
    return render(request,'service_providers/register.html',context)



def new_service(request):
    if request.method!= 'POST':
        form=ServiceProviderForm()
    
    else:
        form=ServiceProviderForm(data=request.POST)
        if form.is_valid():
            new_service=form.save(commit=False)
            new_service.owner=request.user
            new_service.save()
            
            return HttpResponseRedirect(reverse('samples:service_provider'))
    context={'form':form}
    return render(request,'service_providers/new_service.html',context)

clients/templates/clients/index.html
<p> This is client site for car services.</p>



<a href="{% url 'clients:login' %}">LOG IN</a>-

<a href="{% url 'clients:logout' %}">LOG OUT</a>-

<a href="{% url 'clients:register' %}">REGISTER</a>

clients/templates/clients/login.html
<p>Service Providers:</p>
  <form method="POST" action="{%url 'service_providers:login' %}" class="form">
    {% csrf_token %}
    {{form.as_p}}
   
    <button name="submit" class="btn btn-primary">LOG IN</button>
    <input type="hidden" name="next" value="{% url 'samples:service_providers'%}"></input>
   
    
    
  </form>

clients/templates/clients/register.html
<form method='post' action="{% url 'service_providers:register' %}">
      {% csrf_token %}
      {{form.as_p}}
      <button name="submit">Register</button>
      <input type="hidden" name="next" value="{% url 'samples:service_providers' %}"/>
</form>

samples/templates/samples/index.html
<p> This is a website for car service providers and their client.</p>
<p>For service providers: 
<a href="{% url 'service_providers:index' %}">Click here</a>

<p>For clients: 
<a href="{% url 'clients:index' %}">Click here.</a>

samples/templates/samples/service_provider.html
<a href="{% url 'samples:index' %}">Home Page </a>

<p>Service Providers</p>
<ul>
    {% for single in service %}
      <li>
          <p>{{single.service_name}}</p>
          <p>{{single.text}}</p>
      </li>
    {% empty %}
      <li>
          There are no service providers
      </li>
    {% endfor %}
</ul>

<a href="{% url 'service_providers:new_service' %}">Add a new service:</a>

samples/templates/samples/service_providers.html
<p>Service Providers(for clients):</p>
<ul>
    {% for single in services %}
      <li>
          <p>{{single.service_name}}</p>
          <p>{{single.text}}</p>
          <a href="{% url 'samples:send_email' %}">Contact</a>
      </li>
    {% empty %}
      <li>
          There are no service providers
      </li>
    {% endfor %}
</ul>

service_providers/templates/service_providers/index.html
<p> This is service providers site for car services.</p>



<a href="{% url 'service_providers:login' %}">LOG IN</a>-

<a href="{% url 'service_providers:logout' %}">LOG OUT</a>-

<a href="{% url 'service_providers:register' %}">REGISTER</a>

service_providers/templates/service_providers/login.html
<p>Service Providers:</p>
  <form method="POST" action="{%url 'service_providers:login' %}" class="form">
    {% csrf_token %}
    {{form.as_p}}
   
    <button name="submit" class="btn btn-primary">LOG IN</button>
    <input type="hidden" name="next" value="{% url 'samples:service_provider'%}"></input>
   
    
    
    
  </form>

service_providers/templates/service_providers/new_service.html
<p> Add a service name and details:</p>
<form action="{% url 'service_providers:new_service' %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Submit</button>
</form>

service_providers/templates/service_providers/register.html
<form method='post' action="{% url 'service_providers:register' %}">
      {% csrf_token %}
      {{form.as_p}}
      <button name="submit">Register</button>
      <input type="hidden" name="next" value="{% url 'samples:service_provider' %}"/>
</form>